### ISSUE TITLE
Casos de USO

### ISSUE THREAD

**Issue by diegosanchez** [eche33/AlgoTruco#18]
Listar aquí los casos de uso que hay que implementar

**Comment by eche33** [comment]
-Dos jugadores tiran una carta del mismo valor.
-Un jugador canta envido, y el oponente no quiere.
-El jugador que tiró la carta más alta, comienza la ronda siguiente

**Comment by diegosanchez** [comment]
Cada caso de uso va a requerir una prueba de integración. Por tanto tienen que ser lo suficientemente precisos para que se puedan traducir a código.  Para esto cada caso de uso debe detallar un estado inicial (de todas entidades que interactuan) y un resultado esperado (producto de la interacción)

*Dos jugadores tiran una carta del mismo valor.* No es útil a los efectos de generar pruebas de integración.

No entiendo cuál es el objeto de este caso de uso. Aquí ejemplo de casos de uso: [Issue 17](https://github.com/eche33/AlgoTruco/issues/17).

Definan los casos de uso para que los guien en la resolución del problema y no solo para cumplir. No es un capricho mío.

**Comment by eche33** [comment]
Dos jugadores tiran cartas del mismo valor lo puse con el objetivo de
considerar en ese caso quien debería comenzar la ronda siguiente,  ya que
se da una situación de pardas. Es decir,  lo puse porque ahí no me parece
tan simple la decisión de a quien le toca comenzar la siguiente ronda,  ya
que no se puede seguir la idea de que comience el que tiró la carta más
alta.

El vie., nov. 20, 2015 11:59 AM, DiegoS <notifications@github.com> escribió:

> Cada caso de uso va a requerir una prueba de integración. Por tanto tienen
> que ser lo suficientemente precisos para que se puedan traducir a código.
> Para esto cada caso de uso debe detallar un estado inicial (de todas
> entidades que interactuan) y un resultado esperado (producto de la
> interacción)
>
> *Dos jugadores tiran una carta del mismo valor.* No es útil a los efectos
> de generar pruebas de integración.
>
> No entiendo cuál es el objeto de este caso de uso. Aquí ejemplo de casos
> de uso: Issue 17 <https://github.com/eche33/AlgoTruco/issues/17>.
>
> Definan los casos de uso para que los guien en la resolución del problema
> y no solo para cumplir. No es un capricho mío.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eche33/AlgoTruco/issues/18#issuecomment-158424126>.
>
-- 

Rodrigo Etchegaray Campisi
