### ISSUE TITLE
Modelo básico de clases

### ISSUE THREAD

**Issue by cristian-rana** [eche33/AlgoTruco#3]
![modelo basico de clases](https://cloud.githubusercontent.com/assets/15257700/11070932/dc37b2ae-87bc-11e5-8da4-a93fef94d62b.png)

**Comment by diegosanchez** [comment]
Podemos agregarle nombre y multiplicidad a las relaciones?

**Comment by ailugonzalez** [comment]
Nos ponemos a arreglarlo. El diagrama está más completo y ordenado ahora, pero no lo subimos acá todavía. Agregamos lo de nombre y multiplicidad y lo enviamos.

**Comment by ailugonzalez** [comment]
En un rato te los enviamos por mail, junto con el link del informe para que lo veas mejor.

![image](https://cloud.githubusercontent.com/assets/12487632/11609944/fcc65164-9b72-11e5-95a0-57d641b5408d.png)

![image](https://cloud.githubusercontent.com/assets/12487632/11609945/04fe6a1a-9b73-11e5-868f-9aebda40d131.png)

**Comment by diegosanchez** [comment]
Perfecto, no pierdan tiempo con esto. Es suficiente con esto

**Comment by diegosanchez** [comment]
Bien, vieron la necesidad del enumerado de tantos!

Porqué no entidades???

Ver: [Issue#41](https://github.com/eche33/AlgoTruco/issues/41)
