### ISSUE TITLE
Diagrama de estados

### ISSUE THREAD

**Issue by diegosanchez** [eche33/AlgoTruco#43]
En los diagramas de estados necesitarían agregar cuales son los eventos producto por lo cual se realizan las transiciones a los distintos estados.

**Comment by ailugonzalez** [comment]
Consulta: los cambios de estados tienen que ser sí o sí métodos, o basta con la situación? Agrego acá como están ahora (ya los actualizamos en el informe).
![estado-partida](https://cloud.githubusercontent.com/assets/12487632/11755150/12df2dde-a02f-11e5-9a53-de63a12f45ca.jpg)
![estado-ronda](https://cloud.githubusercontent.com/assets/12487632/11755148/12d556b0-a02f-11e5-9a9d-d1bf404359db.jpg)
![vuelta-estado](https://cloud.githubusercontent.com/assets/12487632/11755149/12da6772-a02f-11e5-8896-3527c96aa32e.jpg)

**Comment by diegosanchez** [comment]
sip
